language: python

python:
  - "3.5"

services:
  - docker

before_install:
  - sudo chown 33:33 webserver/container_files
  - pip install requests
  - sudo docker-compose build
  - sudo docker-compose up -d
  - sleep 60

script:
  - pytest
